## 列表推导与可读性

In [1]:
symbols = 'asdfgh'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
codes

[97, 115, 100, 102, 103, 104]

In [8]:
symbols = 'asdfgh'
code2 = [ord(symbol) for symbol in symbols]
code2

[97, 115, 100, 102, 103, 104]

## 列表推导与filter map比较

In [3]:
symbols = 'asdfgh'
%timeit code3 = [ord(symbol) for symbol in symbols if ord(symbol) > 127]

1.08 µs ± 69.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
%timeit code4 = list(filter(lambda c: c > 127, map(ord, symbols)))

2.09 µs ± 184 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 笛卡尔积

In [5]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [10]:
tshirts2 = [(color, size) for color in colors 
                          for size  in sizes ]
tshirts2

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

## 生成器表达式

In [7]:
#生成器表达式相对于列表推导只是将[]换成()
symbols = 'asdfg'
tuple(ord(symbol) for symbol in symbols)

(97, 115, 100, 102, 103)

In [11]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in ('{0} {1}'.format(color, size) for color in colors for size in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


## 元组和记录

In [21]:
lax_coordinates=(33, -118)
city, year, pop, chg, area = ('tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '1234455'), ('BBA', '1234455'), ('ESP', '12435451')]
for passports in sorted(traveler_ids):
    print(passports)

('BBA', '1234455')
('ESP', '12435451')
('USA', '1234455')


## 元组拆包

In [14]:
divmod(20, 8)

(2, 4)

In [15]:
t = (20, 8)
divmod(*t)

(2, 4)

In [16]:
s = (1, 2, 3, 4, 5)
s1, s2, *r = s
r

[3, 4, 5]

In [22]:
*head, s4, s5 = s
head

[1, 2, 3]

## 嵌套元组拆包

In [20]:
infos = [(1,2,3,(4,5)), (6,7,8,(9, 0))]
for a,b,c,(d,e) in infos:
    print(d)

4
9


## 具名元组

In [23]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'J', '11b', (35,139))
tokyo

City(name='Tokyo', country='J', population='11b', coordinates=(35, 139))

In [24]:
City._fields

('name', 'country', 'population', 'coordinates')

In [25]:
Latlong = namedtuple('Latlong', 'lat long')
tokyo = City('Tokyo', 'J', '11b', Latlong(35,139))

In [27]:
t = City._make(tokyo)
t

City(name='Tokyo', country='J', population='11b', coordinates=Latlong(lat=35, long=139))

In [28]:
tokyo._asdict()

OrderedDict([('name', 'Tokyo'),
             ('country', 'J'),
             ('population', '11b'),
             ('coordinates', Latlong(lat=35, long=139))])

# 切片
## 切片和区间会忽略最后一个元素

In [29]:
len(range(3))

3

In [31]:
l = [x for x in range(5)]
l1 = l[:3]#在下标3处分割
l2 = l[3:]
l1

[0, 1, 2]

In [32]:
l2

[3, 4]

## 对对象进行切片

In [33]:
s = 'bicycle'
s[1:3]

'ic'

In [34]:
s[::-1]

'elcycib'

In [35]:
s[::-2]

'eccb'

## 给切片赋值

In [36]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
l[2:5] = [20, 30]

In [39]:
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [42]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [44]:
l[3::2] = [11, 21]
l

[0, 1, 20, 11, 5, 21, 9]

## 建立列表组成的列表

In [45]:
board = [['_']*3 for _ in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [46]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [47]:
weird_board = [['_']*3]*3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [48]:
weird_board[1][2] = 'X'
weird_board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

# 序列的增量赋值

In [49]:
l = [1, 2, 3]
id(l)

2420715691016

In [50]:
l += [3,4,5]
id(l)

2420715691016

In [51]:
l

[1, 2, 3, 3, 4, 5]

In [52]:
t = (1,2,3)
id(t)

2420715677960

In [53]:
t *= 3
t

(1, 2, 3, 1, 2, 3, 1, 2, 3)

In [54]:
id(t)

2420715332680

In [55]:
t = (1, 2, [3, 4])
id(t)

2420715507864

In [58]:
t += [5,6]

TypeError: can only concatenate tuple (not "list") to tuple

In [59]:
t

(1, 2, [3, 4])

# list.sort方法和内置函数sorted

In [60]:
fruits = ['apple', 'strawberry', 'banana', 'grape']
sorted(fruits)

['apple', 'banana', 'grape', 'strawberry']

In [61]:
fruits

['apple', 'strawberry', 'banana', 'grape']

In [62]:
fruits.sort()

In [63]:
fruits

['apple', 'banana', 'grape', 'strawberry']

## 数组

In [65]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.5815779963039402

In [66]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [69]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()

In [70]:
floats2 == floats

True

## 内存视图

In [72]:
numbers = array('h', [1,2,3,4,5])
memv = memoryview(numbers)
memv[-1]

5

In [74]:
memv_oct = memv.cast('B')

In [75]:
memv_oct.tolist()

[1, 0, 2, 0, 3, 0, 4, 0, 5, 0]

In [79]:
memv_oct[4] = 8
numbers

array('h', [1, 2, 8, 4, 8])

## NumPy SciPy

In [80]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
a.shape

(12,)

In [82]:
a.shape = (3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a[2,1]

9

In [84]:
a[:,1]

array([1, 5, 9])

In [85]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [86]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## deque

In [87]:
from collections import deque
dq = deque(range(10), maxlen = 10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
dq.rotate(3)
dq

deque([4, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [90]:
dq.rotate(-2)

In [92]:
dq.extend([11,12,13])
dq

deque([9, 0, 1, 2, 3, 4, 5, 11, 12, 13])

In [93]:
dq.extendleft([14,15,16])
dq

deque([16, 15, 14, 9, 0, 1, 2, 3, 4, 5])